import type { Metadata } from 'next';
import { DM_Sans, Inter, Rubik } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });
const rubik = Rubik({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="w-screen h-screen" lang="en">
      <head></head>
      <body className={inter.className + 'h-full w-full'}>
        <Navbar />
        {children}

        <Script
          type="module"
          src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
        ></Script>
        <Script
          noModule
          src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
        ></Script>
      </body>
    </html>
  );
}
